version: '3.9'

services:
  backend:
    volumes:
      - dev-static-data:/vol/web
    env_file:
      - .env
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db

  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend:/app/build

  nginx:
    build:
      context: ./nginx
    volumes:
      - dev-static-data:/vol/web
      - frontend:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
volumes:
  dev-static-data:
  frontend: