version: '3.9'

services:
  backend:
    volumes:
      - dev-static-data:/vol/web
    env_file:
      - .env
    build:
      context: ./backend
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    container_name: postgres_db

  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend:/app/build
    depends_on:
      - backend

  nginx:
    # build:
    #   context: ./nginx
    image: nginx:latest
    ports:
      - 80:8080
    restart: always
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - dev-static-data:/vol/web
      - frontend:/var/www/frontend
    depends_on:
      - backend
      - frontend
volumes:
  dev-static-data:
  frontend:
