# Generated by Django 4.2.6 on 2023-11-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact_email_profile_is_latest_alter_contact_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(default=' '),
        ),
    ]
