# Generated by Django 4.2.6 on 2023-11-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_techcategory_skills_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='skills',
            field=models.ManyToManyField(blank=True, to='core.skills'),
        ),
    ]
