# Generated by Django 4.2.6 on 2023-11-17 10:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_projects_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=core.models.skill_image_file_path)),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='images',
            field=models.ManyToManyField(null=True, to='core.image'),
        ),
    ]
