# Generated by Django 4.2.6 on 2023-11-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_image_projects_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='text',
            field=models.CharField(default='Image', max_length=100),
        ),
    ]
