# Generated by Django 4.2.6 on 2023-11-18 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_visitor_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
