# Generated by Django 4.2.6 on 2023-11-30 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contactform_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browsehistory',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.visitor'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.visitor'),
        ),
    ]
