# Generated by Django 4.2.6 on 2023-12-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_browsehistory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='images',
            field=models.ManyToManyField(blank=True, to='core.image'),
        ),
    ]
