---
name: Checks

on: [push]

jobs:
    test-lint:
        name: Backend Tests and Lint
        runs-on: ubuntu-20.04

        services:
          postgres:
            image: postgres
            env:
              POSTGRES_HOST: db
              POSTGRES_PASSWORD: gonnachange
              POSTGRES_USER: rootuser
              POSTGRES_DB: dbname
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Create .env file
              run: cp .env.sample .env

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'

            - name: Install Dependencies
              run: |
                pip install -r backend/requirements.txt
                pip install -r backend/requirements.dev.txt

            - name: Linting Check
              run: |
                cd backend
                flake8

            - name: Backend Test
              run: |
                cd backend
                python manage.py makemigrations
                python manage.py migrate
                python manage.py test
